**Neekitasingh Rajput** <br>
**2441339** <br>
**LAB TEST 2**

In [1]:
#import necessasry libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
#load the dataset

data = pd.read_csv("salaries.csv")
df = pd.DataFrame(data)
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

**Q1. Exploratory Data Analysis**

In [3]:
#1.
#dataset shape (rows, columns)

df.shape

(16, 4)

In [4]:
#column names

df.columns

Index(['company', 'job', 'degree', 'salary_more_then_100k'], dtype='object')

In [5]:
#2.
#data types of all columns

df.dtypes

company                  object
job                      object
degree                   object
salary_more_then_100k     int64
dtype: object

In [6]:
#3.
#missing values check

df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [7]:
#Thus, No missing values.

In [8]:
#4.
#Count/summary of unique categories for company, job, degree

cols = ['company','job','degree']
for col in cols:
    print(col,":")
    print("\nCount of unique categories:", df[col].nunique())
    print("\nUnique Categories:", df[col].unique(),"\n")

company :

Count of unique categories: 3

Unique Categories: ['google' 'abc pharma' 'facebook']

job :

Count of unique categories: 3

Unique Categories: ['sales executive' 'business manager' 'computer programmer']

degree :

Count of unique categories: 2

Unique Categories: ['bachelors' 'masters']

**Q2) Data Preprocessing**

In [9]:
#1. Separate features X and target y (salary_more_then_100k)

X = df.drop('salary_more_then_100k',axis=1)
y = pd.DataFrame(df['salary_more_then_100k'])

In [10]:
X

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [11]:
y

    salary_more_then_100k
0                       0
1                       0
2                       1
3                       1
4                       0
5                       1
6                       0
7                       0
8                       0
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      1

In [16]:
#2. Split data into train and test sets (recommended: 80/20 or 75/25) with

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [12]:
#3. Encode categorical variables

categorical_cols = df.select_dtypes(include = ['object']).columns
categorical_cols

Index(['company', 'job', 'degree'], dtype='object')

In [13]:
le = LabelEncoder()
df['degree'] = le.fit_transform(df['degree']) #as degree is an ordinal column
df = pd.get_dummies(df) #for other categorical columns

In [14]:
df

,degree,salary_more_then_100k,company_abc pharma,company_facebook,company_google,job_business manager,job_computer programmer,job_sales executive
0,0,0,False,False,True,False,False,True
1,1,0,False,False,True,False,False,True
2,0,1,False,False,True,True,False,False
3,1,1,False,False,True,True,False,False
4,0,0,False,False,True,False,True,False
5,1,1,False,False,True,False,True,False
6,1,0,True,False,False,False,False,True
7,0,0,True,False,False,False,True,False
8,0,0,True,False,False,True,False,False
9,1,1,True,False,False,True,False,False
10,0,1,False,True,False,False,False,True
11,1,1,False,True,False,False,False,True
12,0,1,False,True,False,True,False,False
13,1,1,False,True,False,True,False,False
14,0,1,False,True,False,False,True,False
15,1,1,False,True,False,False,True,False

In [17]:
#4. Print the shape of X_train and X_test after preprocessing (number of rows and columns)

In [23]:
print("Training dataset:", X_train.shape)
print("Test dataset:", X_test.shape)

Training dataset: (12, 7)
Test dataset: (4, 7)

**Q3) Model Building (Decision Tree)**

In [25]:
dt = DecisionTreeClassifier(criterion = "entropy")
dt.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

**Q4) Model Evaluation**

In [26]:
dt_pred = dt.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)

print("Model Accuracy:", dt_acc)

Model Accuracy: 0.75

In [27]:
#Confusion matrix

cm = confusion_matrix(y_test, dt_pred)
print(cm)

[[2 0]
 [1 1]]

In [28]:
#classification_report

cr = classification_report(y_test, dt_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.50      0.67         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4

**Q5) Conclusion**

The decision tree classifier works on the concept of entropy of the dataset. <br>
It is one of the significant Classification Machine Learning Model which creates a tree like decision algorithm for classifying the data into different classes. <br>
We first load the dataset. Perform the Exploratory Data Analysis, understand the data well, <br>
Then we do some preprocessing like scaling it, handling missing values, encoding the categorical into numerical values, <br>
so as to simplify the datset and make it ready for training our model. <br>
<br>
Then we apply our model, train it, test it and thus analyse if the model could do the classification or not. <br>
That's how all the Machine Learning algorithms work.