Neekitasingh Rajput
2441339
LAB TEST-1
#(Set A)

Machine Learning LAB

In [1]:
#A. 
#Import the required library and load Students.csv into a Dataframe named df_students.
#Display the first 5 rows of the DataFrame.

import pandas as pd #necessary library

data = pd.read_csv(r"C:\Users\bca.lab21\Desktop\students.csv") #path of the file
df_students = pd.DataFrame(data)

df_students.head()

  Student_ID   Name Dept  Semester  Internals  Finals  Attendance_Percent
0         S1   Anuj  CSE         2         18      56                92.0
1         S2  Priya  CSE         2         20      60                95.0
2         S3  Rohan  ECE         2         17      48                80.0
3         S4   Neha  CSE         2         19      50                85.0
4         S5  Aarav   IT         2         16      45                78.0

<h5>
    Obs: pandas library is the library that is used for Data Manipulation. df.head() gives us the view of first 5 rows in our Data.
</h5>

In [2]:
#B.
#Write code to display the number of rows and columns in df_students.

print("(Rows, Columns) = ",df_students.shape)

(Rows, Columns) =  (10, 7)

<h5>
Obs: No. of Rows and Columns can be obtained from the shape of the dataset.
</h5>

In [3]:
#C. 
#Obtain the summary statistics for the columns Internals and Finals. Write the code.

print("\nSummary statistics for the columns Internals and Finals:\n")
df_students[["Internals","Finals"]].describe()

Summary statistics for the columns Internals and Finals:

       Internals     Finals
count  10.000000  10.000000
mean   17.600000  49.300000
std     2.065591   7.846443
min    14.000000  35.000000
25%    16.250000  45.750000
50%    18.000000  49.500000
75%    19.000000  55.000000
max    20.000000  60.000000

<h5>
    Obs: Summary statistics of any numeric column is obtained using describe() function.
</h5>

In [4]:
#D.
#Select and Display all rows where Attendance_Percent > 85.

df_students[df_students["Attendance_Percent"] > 85]

  Student_ID     Name Dept  Semester  Internals  Finals  Attendance_Percent
0         S1     Anuj  CSE         2         18      56                92.0
1         S2    Priya  CSE         2         20      60                95.0
7         S8     Isha   IT         2         19      52                88.0
9        S10  Reyansh  ECE         2         20      58                96.0

<h5>
    Obs: Filtering helps us view a required data with a specified condition.
</h5>

In [5]:
#E.
#In the dataset, Attendance_Percent has a missing Value.

#(i). Write code to identify rows where Attendance_Percent is missing.

print("\nRow with missing Attendance Percent:")
df_students[df_students["Attendance_Percent"].isnull() == True]

Row with missing Attendance Percent:

  Student_ID  Name Dept  Semester  Internals  Finals  Attendance_Percent
8         S9  Tara  CSE         2         18      49                 NaN

<h5>
    Obs: isnull checks for us if there is any missing data in our dataset.
</h5>

In [6]:
#(ii). Fill the missing Attendance_Percent with the mean attendance of the column.

mean_att = df_students["Attendance_Percent"].mean()
print("\nMean attendance:", mean_att)
df_students = df_students.fillna(mean_att)
df_students

Mean attendance: 84.33333333333333

  Student_ID     Name Dept  Semester  Internals  Finals  Attendance_Percent
0         S1     Anuj  CSE         2         18      56           92.000000
1         S2    Priya  CSE         2         20      60           95.000000
2         S3    Rohan  ECE         2         17      48           80.000000
3         S4     Neha  CSE         2         19      50           85.000000
4         S5    Aarav   IT         2         16      45           78.000000
5         S6    Meera  ECE         2         15      40           75.000000
6         S7    Kabir  CSE         2         14      35           70.000000
7         S8     Isha   IT         2         19      52           88.000000
8         S9     Tara  CSE         2         18      49           84.333333
9        S10  Reyansh  ECE         2         20      58           96.000000

<h5>
    Obs: mean can be calculated and then be imputed for numeric columns at the missing places.
</h5>

In [7]:
#(iii). Create a new column Total_Marks = Internals + Finals and display the first 5 rows of the updated DataFrame.

df_students["Total Marks"] = df_students["Internals"] + df_students["Finals"]
df_students.head()

,Student_ID,Name,Dept,Semester,Internals,Finals,Attendance_Percent,Total Marks
0,S1,Anuj,CSE,2,18,56,92.0,74
1,S2,Priya,CSE,2,20,60,95.0,80
2,S3,Rohan,ECE,2,17,48,80.0,65
3,S4,Neha,CSE,2,19,50,85.0,69
4,S5,Aarav,IT,2,16,45,78.0,61

<h5>
    Obs: New columns with calculated columns help us infer more about the dataset.
</h5>