In [1]:
#Question 1
# created dataset of 20 records with random values..
data = {
    "Patient_ID": ["P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",
                   "P11","P12","P13","P14","P15","P16","P17","P18","P19","P20"],

    "Department": ["Cardiology","Neurology","Orthopedics","Pediatrics","Cardiology",
                   "Neurology","Orthopedics","Pediatrics","Cardiology","Orthopedics",
                   "Neurology","Pediatrics","Cardiology","Orthopedics","Pediatrics",
                   "Neurology","Cardiology","Pediatrics","Neurology","Orthopedics"],

    "Gender": ["Male","Female","Male","Female","Non-binary",
               "Male","Female","Female","Male","Male",
               "Female","Non-binary","Female","Male","Female",
               "Male","Non-binary","Female","Male","Female"],

    "Age": [45,32,67,5,54,29,72,14,63,40,35,10,51,60,22,48,70,7,56,33],

    "Admission_Date": ["2023-01-10","2022-11-05","2024-03-22","2023-08-15","2022-06-30",
                       "2024-01-11","2023-09-10","2022-12-01","2023-05-20","2024-02-14",
                       "2023-10-05","2022-07-19","2024-01-30","2023-03-09","2022-09-29",
                       None,"2024-04-01","2023-11-22", None, "2022-05-18"],

    "Discharge_Date": ["2023-01-15","2022-11-12","2024-03-29", None, "2022-07-04",
                       "2024-01-18","2023-09-14","2022-12-05", None, "2024-02-20",
                       "2023-10-09","2022-07-25","2024-02-04","2023-03-12", None,
                       "2024-02-01","2024-04-05","2023-11-28","2023-06-20", None],

    "Diagnosis_Code": ["D1","D2","D3","D4","D1","D2","D3","D4","D1","D2",
                       None,"D4","D1","D3","D4","D2","D1", None,"D3","D2"],

    "Length_of_Stay_Days": [5,7,6, None,4,7,4,2, None,6,3,5,5,3,2,1,6,3, None,4],

    "Total_Bill": [20000,35000,150000, None,22000,30000,18000,12000, None,45000,
                   17000,25000,50000,32000,14000, None,60000,28000,19000, None],

    "Insurance_Type": ["Private","Government","Self-pay","Private","Government",
                       "Self-pay","Private","Government", None,"Private",
                       "Self-pay","Government","Private","Self-pay","Government",
                       None,"Private","Government","Self-pay","Government"]
}

In [2]:
#Question 2
#imported with pandas and displayed it

import pandas as pd
import numpy as np

df = pd.DataFrame(data)

# Save CSV
df.to_csv("hospital_admissions.csv")

df = pd.read_csv("hospital_admissions.csv")
df

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,NaN,NaN,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.0,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.0,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.0,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,NaN,D1,NaN,NaN,NaN
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.0,45000.0,Private
10,10,P11,Neurology,Female,35,2023-10-05,2023-10-09,NaN,3.0,17000.0,Self-pay
11,11,P12,Pediatrics,Non-binary,10,2022-07-19,2022-07-25,D4,5.0,25000.0,Government
12,12,P13,Cardiology,Female,51,2024-01-30,2024-02-04,D1,5.0,50000.0,Private
13,13,P14,Orthopedics,Male,60,2023-03-09,2023-03-12,D3,3.0,32000.0,Self-pay
14,14,P15,Pediatrics,Female,22,2022-09-29,NaN,D4,2.0,14000.0,Government
15,15,P16,Neurology,Male,48,NaN,2024-02-01,D2,1.0,NaN,NaN
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.0,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,NaN,3.0,28000.0,Government
18,18,P19,Neurology,Male,56,NaN,2023-06-20,D3,NaN,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,NaN,D2,4.0,NaN,Government

In [3]:
#a. First 10 rows, head , tail

df.head(10)

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,NaN,NaN,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.0,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.0,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.0,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,NaN,D1,NaN,NaN,NaN
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.0,45000.0,Private

In [4]:
df.head()

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,NaN,NaN,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government

In [5]:
df.tail()

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
15,15,P16,Neurology,Male,48,NaN,2024-02-01,D2,1.0,NaN,NaN
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.0,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,NaN,3.0,28000.0,Government
18,18,P19,Neurology,Male,56,NaN,2023-06-20,D3,NaN,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,NaN,D2,4.0,NaN,Government

In [6]:
#b. Shape of the Data

df.shape

(20, 11)

In [7]:
#c. Columns list + unique values of one categorical column

print(df.columns)

# For example: Department
print("\n", df["Department"].nunique())
print("\n", df["Department"].unique())

Index(['Unnamed: 0', 'Patient_ID', 'Department', 'Gender', 'Age',
       'Admission_Date', 'Discharge_Date', 'Diagnosis_Code',
       'Length_of_Stay_Days', 'Total_Bill', 'Insurance_Type'],
      dtype='object')

 4

 ['Cardiology' 'Neurology' 'Orthopedics' 'Pediatrics']

In [8]:
#d. Null-value check per column

df.isnull().sum()

Unnamed: 0             0
Patient_ID             0
Department             0
Gender                 0
Age                    0
Admission_Date         2
Discharge_Date         4
Diagnosis_Code         2
Length_of_Stay_Days    3
Total_Bill             4
Insurance_Type         2
dtype: int64

In [9]:
#e. Stored as a DataFrame and displayed

df

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,NaN,NaN,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.0,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.0,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.0,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,NaN,D1,NaN,NaN,NaN
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.0,45000.0,Private
10,10,P11,Neurology,Female,35,2023-10-05,2023-10-09,NaN,3.0,17000.0,Self-pay
11,11,P12,Pediatrics,Non-binary,10,2022-07-19,2022-07-25,D4,5.0,25000.0,Government
12,12,P13,Cardiology,Female,51,2024-01-30,2024-02-04,D1,5.0,50000.0,Private
13,13,P14,Orthopedics,Male,60,2023-03-09,2023-03-12,D3,3.0,32000.0,Self-pay
14,14,P15,Pediatrics,Female,22,2022-09-29,NaN,D4,2.0,14000.0,Government
15,15,P16,Neurology,Male,48,NaN,2024-02-01,D2,1.0,NaN,NaN
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.0,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,NaN,3.0,28000.0,Government
18,18,P19,Neurology,Male,56,NaN,2023-06-20,D3,NaN,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,NaN,D2,4.0,NaN,Government

In [10]:
#f. Fill nulls in object/categorical columns with 'na'

df_cat_filled = df.copy()

cat_cols = df_cat_filled.select_dtypes(include="object").columns
df_cat_filled[cat_cols] = df_cat_filled[cat_cols].fillna("na")

df_cat_filled

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,na,D4,NaN,NaN,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.0,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.0,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.0,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,na,D1,NaN,NaN,na
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.0,45000.0,Private
10,10,P11,Neurology,Female,35,2023-10-05,2023-10-09,na,3.0,17000.0,Self-pay
11,11,P12,Pediatrics,Non-binary,10,2022-07-19,2022-07-25,D4,5.0,25000.0,Government
12,12,P13,Cardiology,Female,51,2024-01-30,2024-02-04,D1,5.0,50000.0,Private
13,13,P14,Orthopedics,Male,60,2023-03-09,2023-03-12,D3,3.0,32000.0,Self-pay
14,14,P15,Pediatrics,Female,22,2022-09-29,na,D4,2.0,14000.0,Government
15,15,P16,Neurology,Male,48,na,2024-02-01,D2,1.0,NaN,na
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.0,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,na,3.0,28000.0,Government
18,18,P19,Neurology,Male,56,na,2023-06-20,D3,NaN,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,na,D2,4.0,NaN,Government

In [11]:
#g. Fill nulls in numeric columns with mean

df_mean_filled = df.copy()

num_cols = df_mean_filled.select_dtypes(include=["float64", "int64"]).columns
df_mean_filled[num_cols] = df_mean_filled[num_cols].fillna(df_mean_filled[num_cols].mean())

df_mean_filled

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.000000,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.000000,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.000000,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,4.294118,36062.5,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.000000,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.000000,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.000000,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.000000,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,NaN,D1,4.294118,36062.5,NaN
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.000000,45000.0,Private
10,10,P11,Neurology,Female,35,2023-10-05,2023-10-09,NaN,3.000000,17000.0,Self-pay
11,11,P12,Pediatrics,Non-binary,10,2022-07-19,2022-07-25,D4,5.000000,25000.0,Government
12,12,P13,Cardiology,Female,51,2024-01-30,2024-02-04,D1,5.000000,50000.0,Private
13,13,P14,Orthopedics,Male,60,2023-03-09,2023-03-12,D3,3.000000,32000.0,Self-pay
14,14,P15,Pediatrics,Female,22,2022-09-29,NaN,D4,2.000000,14000.0,Government
15,15,P16,Neurology,Male,48,NaN,2024-02-01,D2,1.000000,36062.5,NaN
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.000000,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,NaN,3.000000,28000.0,Government
18,18,P19,Neurology,Male,56,NaN,2023-06-20,D3,4.294118,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,NaN,D2,4.000000,36062.5,Government

In [12]:
#h. Fill nulls in numeric columns with median

df_median_filled = df.copy()

num_cols = df_median_filled.select_dtypes(include=["float64", "int64"]).columns
df_median_filled[num_cols] = df_median_filled[num_cols].fillna(df_median_filled[num_cols].median())

df_median_filled

,Unnamed: 0,Patient_ID,Department,Gender,Age,Admission_Date,Discharge_Date,Diagnosis_Code,Length_of_Stay_Days,Total_Bill,Insurance_Type
0,0,P1,Cardiology,Male,45,2023-01-10,2023-01-15,D1,5.0,20000.0,Private
1,1,P2,Neurology,Female,32,2022-11-05,2022-11-12,D2,7.0,35000.0,Government
2,2,P3,Orthopedics,Male,67,2024-03-22,2024-03-29,D3,6.0,150000.0,Self-pay
3,3,P4,Pediatrics,Female,5,2023-08-15,NaN,D4,4.0,26500.0,Private
4,4,P5,Cardiology,Non-binary,54,2022-06-30,2022-07-04,D1,4.0,22000.0,Government
5,5,P6,Neurology,Male,29,2024-01-11,2024-01-18,D2,7.0,30000.0,Self-pay
6,6,P7,Orthopedics,Female,72,2023-09-10,2023-09-14,D3,4.0,18000.0,Private
7,7,P8,Pediatrics,Female,14,2022-12-01,2022-12-05,D4,2.0,12000.0,Government
8,8,P9,Cardiology,Male,63,2023-05-20,NaN,D1,4.0,26500.0,NaN
9,9,P10,Orthopedics,Male,40,2024-02-14,2024-02-20,D2,6.0,45000.0,Private
10,10,P11,Neurology,Female,35,2023-10-05,2023-10-09,NaN,3.0,17000.0,Self-pay
11,11,P12,Pediatrics,Non-binary,10,2022-07-19,2022-07-25,D4,5.0,25000.0,Government
12,12,P13,Cardiology,Female,51,2024-01-30,2024-02-04,D1,5.0,50000.0,Private
13,13,P14,Orthopedics,Male,60,2023-03-09,2023-03-12,D3,3.0,32000.0,Self-pay
14,14,P15,Pediatrics,Female,22,2022-09-29,NaN,D4,2.0,14000.0,Government
15,15,P16,Neurology,Male,48,NaN,2024-02-01,D2,1.0,26500.0,NaN
16,16,P17,Cardiology,Non-binary,70,2024-04-01,2024-04-05,D1,6.0,60000.0,Private
17,17,P18,Pediatrics,Female,7,2023-11-22,2023-11-28,NaN,3.0,28000.0,Government
18,18,P19,Neurology,Male,56,NaN,2023-06-20,D3,4.0,19000.0,Self-pay
19,19,P20,Orthopedics,Female,33,2022-05-18,NaN,D2,4.0,26500.0,Government

# Short Reflection

<font color="blue">
<ul>
    <li>The hospital admissions dataset was created with 20 structured records, including controlled null values across dates, billing, diagnosis, and insurance fields.</li>
    <li>Initial inspection using head, tail, shape, and column listing confirmed that the dataset was correctly formatted and ready for preprocessing.</li>
    <li>Categorical exploration (e.g., Department, Insurance_Type) helped verify category diversity and identify missing labels for later cleaning.</li>
    <li>Null-value analysis revealed gaps in Discharge_Date, Length_of_Stay_Days, Total_Bill, and Diagnosis_Code, reflecting realistic hospital data inconsistencies.</li>
    <li>Categorical nulls were filled with the placeholder 'na' to maintain consistency during analysis and future encoding.</li>
    <li>Numeric nulls were imputed using both mean and median values, allowing comparison between different strategies for handling medical dataset variability.</li>
    <li>Overall, the preprocessing steps resulted in a clean, well-structured dataset suitable for further analysis, visualization, or modeling.</li>
</ul>
</font>